#!/usr/bin/env tsx
/**
 * Renders auto-extracted reference pages from static/sdk-manifest.json.
 *
 * Currently renders:
 *   - docs/reference/contracts/base-mainnet.md
 *   - docs/reference/contracts/base-sepolia.md
 *   - docs/reference/cli/index.md  (TS + Python command tables)
 *   - docs/reference/mcp-server/index.md  (20 tools by layer)
 *
 * Other /reference/ pages stay hand-written for v1 per PHASE3_DECISIONS Q3
 * (auto-extract SDK API + errors is a post-v1 stream).
 *
 * Run via:
 *   npm run render-reference
 *
 * Wired into the CI workflow (truth-ledger-refresh.yml) so manifest
 * regeneration + reference re-render ship together as a single PR.
 *
 * Does NOT run in Vercel prebuild. Like truth-ledger itself, this script
 * needs the manifest to exist (it always does, since it's committed).
 * Vercel just deploys whatever rendered pages are committed.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const ROOT = path.resolve(__dirname, '..');
const MANIFEST_PATH = path.join(ROOT, 'static', 'sdk-manifest.json');
const DOCS_DIR = path.join(ROOT, 'docs');

interface ContractEntry {
  address: string;
  verified_status: string;
  verified_at?: string;
  deployment_claimed_verified?: boolean;
  deploy_block?: number;
  deploy_tx?: string;
  explorer_url?: string;
  compiler?: string;
  status?: 'deprecated';
  note?: string;
  platformFeeBps?: number;
  disputeBondBps?: number;
  minDisputeBondMicroUSDC?: number;
  owner?: string;
}

interface ErrorEntry {
  class_name: string;
  parent: string;
  code: string | null;
  source_file: string;
}

interface SdkSymbol {
  name: string;
  kind: string;
  tier: string;
  tier_from_source?: boolean;
  doc_summary?: string;
}

interface TierEntry {
  ts?: string;
  python?: string;
  sync_status: string;
}

interface AgirailsState {
  name: string;
  value: number;
  description: string;
}

interface OnboardingQuestion {
  id: string;
  ask: string;
  type: string;
  options?: string[];
  default?: string | number;
  condition?: string;
  advanced?: boolean;
}

interface ProtocolData {
  protocol: string;
  version: string;
  spec: string;
  network: string;
  currency: string;
  fee: string;
  sdk: { npm?: string; pip?: string };
  capabilities: string[];
  states: AgirailsState[];
  onboarding: { execution: string; questions: OnboardingQuestion[] };
}

interface Manifest {
  _generatedAt: string;
  _sourceVersions: Record<string, string>;
  protocol: ProtocolData;
  contracts: Record<string, {
    chainId: number;
    blockExplorer: string;
    contracts: Record<string, ContractEntry>;
  }>;
  cli: {
    ts: { binary: string; commands: { name: string; qualified_name: string; subcommands?: { name: string; qualified_name: string }[] }[]; };
    python: { binary: string; commands: { name: string; qualified_name: string; subcommands?: { name: string; qualified_name: string }[] }[]; };
    cross_sdk: { ts_only: string[]; python_only: string[] };
    counts: { ts: number; python: number };
  };
  mcp: {
    package_version: string;
    total: number;
    layers: {
      discovery: { name: string; description: string; read_only: boolean; destructive: boolean }[];
      runtime: { name: string; description: string; read_only: boolean; destructive: boolean }[];
      protocol: { name: string; description: string; read_only: boolean; destructive: boolean }[];
    };
  };
  errors: {
    ts: ErrorEntry[];
    python: ErrorEntry[];
    cross_sdk: { ts_only: string[]; python_only: string[] };
    counts: { ts: number; python: number };
  };
  sdk_api: {
    ts: { package_name: string; package_version: string; source_file: string; symbols: SdkSymbol[]; count: number };
    python: { package_name: string; package_version: string; symbols: SdkSymbol[]; count: number };
    cross_sdk: { ts_only: string[]; python_only: string[]; counts: { ts_only: number; python_only: number } };
  };
  tiers: Record<string, TierEntry>;
}

const GENERATED_BANNER = '<!-- GENERATED by scripts/render-reference.ts from static/sdk-manifest.json. Do not edit by hand. -->';

function loadManifest(): Manifest {
  if (!fs.existsSync(MANIFEST_PATH)) {
    throw new Error(`Manifest not found: ${MANIFEST_PATH}. Run npm run truth-ledger first.`);
  }
  return JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8'));
}

function verifiedBadge(status: string): string {
  switch (status) {
    case 'exact_match': return '✅ Sourcify exact match';
    case 'partial_match': return '⚠️ Sourcify partial match';
    case 'no_match': return '❌ Sourcify no match';
    case 'deployment_claim_only': return '⏳ Deployment-claim only (Sourcify unreachable at last check)';
    case 'unverified': return '🔓 Not verified';
    case 'external_token': return '🏛️ External token (Circle USDC etc.)';
    default: return status;
  }
}

function renderContractsPage(
  network: 'base-mainnet' | 'base-sepolia',
  data: Manifest['contracts'][string],
  generatedAt: string,
): string {
  const title = network === 'base-mainnet' ? 'Base mainnet contracts (chain 8453)' : 'Base Sepolia contracts (chain 84532)';
  const description = network === 'base-mainnet'
    ? 'Production ACTP kernel + supporting contracts on Base mainnet, with live Sourcify exact-match verification.'
    : 'Test ACTP kernel + supporting contracts on Base Sepolia, with live Sourcify exact-match verification.';

  const lines: string[] = [];
  lines.push('---');
  lines.push(`slug: /reference/contracts/${network}`);
  lines.push(`title: "${title}"`);
  lines.push(`description: "${description}"`);
  lines.push('schema_type: APIReference');
  lines.push(`last_verified: ${generatedAt.slice(0, 10)}`);
  lines.push('auto_extracted_source: "static/sdk-manifest.json"');
  lines.push('stability: stable');
  lines.push('last_breaking_change: 2026-05-19');
  lines.push('tags: [reference, contracts, ' + network + ', auto-extracted]');
  lines.push('sidebar_position: ' + (network === 'base-mainnet' ? 1 : 2));
  lines.push('---');
  lines.push('');
  lines.push(GENERATED_BANNER);
  lines.push('');
  lines.push(`# ${title}`);
  lines.push('');
  lines.push(description);
  lines.push('');
  lines.push(`**Chain ID**: \`${data.chainId}\` · **Block explorer**: [${data.blockExplorer}](${data.blockExplorer}) · **Manifest generated**: ${generatedAt.slice(0, 19).replace('T', ' ')} UTC`);
  lines.push('');

  for (const [name, c] of Object.entries(data.contracts)) {
    lines.push(`## ${name}`);
    lines.push('');
    lines.push(`**Address**: [\`${c.address}\`](${c.explorer_url ?? data.blockExplorer + '/address/' + c.address})`);
    lines.push('');
    lines.push(`**Verification**: ${verifiedBadge(c.verified_status)}` + (c.verified_at ? ` _(checked ${c.verified_at.slice(0, 19).replace('T', ' ')} UTC)_` : ''));
    lines.push('');
    if (c.status === 'deprecated') {
      lines.push(':::warning Deprecated');
      lines.push('This contract is marked deprecated and retained only for legacy integration paths. Do not use for new code.');
      lines.push(':::');
      lines.push('');
    }
    const metaRows: string[] = [];
    if (c.deploy_block !== undefined) metaRows.push(`| Deploy block | \`${c.deploy_block}\` |`);
    if (c.deploy_tx) metaRows.push(`| Deploy tx | [\`${c.deploy_tx.slice(0, 14)}…\`](${data.blockExplorer}/tx/${c.deploy_tx}) |`);
    if (c.compiler) metaRows.push(`| Solidity compiler | \`${c.compiler}\` |`);
    if (c.platformFeeBps !== undefined) metaRows.push(`| platformFeeBps | \`${c.platformFeeBps}\` (${c.platformFeeBps / 100}%) |`);
    if (c.disputeBondBps !== undefined) metaRows.push(`| disputeBondBps | \`${c.disputeBondBps}\` (${c.disputeBondBps / 100}%) |`);
    if (c.minDisputeBondMicroUSDC !== undefined) metaRows.push(`| MIN_DISPUTE_BOND | \`${c.minDisputeBondMicroUSDC / 1_000_000}\` USDC |`);
    if (c.owner) metaRows.push(`| Owner | \`${c.owner}\` |`);
    if (metaRows.length > 0) {
      lines.push('| Field | Value |');
      lines.push('|---|---|');
      lines.push(...metaRows);
      lines.push('');
    }
    if (c.note) {
      lines.push(`> ${c.note.replace(/\n/g, ' ')}`);
      lines.push('');
    }
  }

  lines.push('## See also');
  lines.push('');
  lines.push('- [Truth-ledger manifest (raw JSON)](/sdk-manifest.json)');
  lines.push(`- [${network === 'base-mainnet' ? 'Base Sepolia contracts' : 'Base mainnet contracts'}](/reference/contracts/${network === 'base-mainnet' ? 'base-sepolia' : 'base-mainnet'})`);
  lines.push('- [Protocol fees + dispute bonds](/protocol/fees)');
  lines.push('- [Escrow mechanism](/protocol/escrow)');
  lines.push('');

  return lines.join('\n');
}

function renderCliPage(cli: Manifest['cli'], generatedAt: string): string {
  const lines: string[] = [];
  lines.push('---');
  lines.push('slug: /reference/cli');
  lines.push('title: "actp CLI reference"');
  lines.push('description: "All actp subcommands, args, and options. Auto-extracted from sdk-js (Commander) + python-sdk-v2 (Typer) sources via the truth-ledger pipeline."');
  lines.push('schema_type: APIReference');
  lines.push(`last_verified: ${generatedAt.slice(0, 10)}`);
  lines.push('auto_extracted_source: "static/sdk-manifest.json"');
  lines.push('stability: stable');
  lines.push('last_breaking_change: 2026-05-19');
  lines.push('tags: [reference, cli, auto-extracted]');
  lines.push('sidebar_position: 1');
  lines.push('---');
  lines.push('');
  lines.push(GENERATED_BANNER);
  lines.push('');
  lines.push('# actp CLI reference');
  lines.push('');
  lines.push(`**TypeScript SDK CLI** (\`${cli.ts.binary}\`): ${cli.counts.ts} commands · **Python SDK CLI** (\`${cli.python.binary}\`): ${cli.counts.python} commands · **Manifest generated**: ${generatedAt.slice(0, 19).replace('T', ' ')} UTC`);
  lines.push('');
  lines.push('Both SDKs expose the same `actp` binary, with the command tree extracted directly from each runtime\'s Commander/Typer registration.');
  lines.push('');

  const renderCmds = (sdk: 'TS' | 'Python', commands: typeof cli.ts.commands) => {
    lines.push(`## ${sdk} CLI commands`);
    lines.push('');
    lines.push('| Command | Subcommands |');
    lines.push('|---|---|');
    for (const c of commands) {
      const subs = c.subcommands && c.subcommands.length > 0
        ? c.subcommands.map((s) => `\`${s.qualified_name}\``).join(', ')
        : '_(none)_';
      lines.push(`| \`actp ${c.name}\` | ${subs} |`);
    }
    lines.push('');
  };

  renderCmds('TS', cli.ts.commands);
  renderCmds('Python', cli.python.commands);

  if (cli.cross_sdk.ts_only.length > 0 || cli.cross_sdk.python_only.length > 0) {
    lines.push('## Cross-SDK divergences');
    lines.push('');
    if (cli.cross_sdk.ts_only.length > 0) {
      lines.push(`**TypeScript-only** (${cli.cross_sdk.ts_only.length}): ${cli.cross_sdk.ts_only.map((c) => `\`${c}\``).join(', ')}`);
      lines.push('');
    }
    if (cli.cross_sdk.python_only.length > 0) {
      lines.push(`**Python-only** (${cli.cross_sdk.python_only.length}): ${cli.cross_sdk.python_only.map((c) => `\`${c}\``).join(', ')}`);
      lines.push('');
    }
  }

  lines.push('## See also');
  lines.push('');
  lines.push('- [Reference overview](/reference)');
  lines.push('- [Truth-ledger manifest (raw JSON)](/sdk-manifest.json)');
  lines.push('');

  return lines.join('\n');
}

function renderMcpPage(mcp: Manifest['mcp'], generatedAt: string): string {
  const lines: string[] = [];
  lines.push('---');
  lines.push('slug: /reference/mcp-server');
  lines.push('title: "MCP server reference (@agirails/mcp-server)"');
  lines.push(`description: "All ${mcp.total} MCP tools across three layers (discovery, runtime, protocol bootstrap). Auto-extracted from the mcp-server TOOLS array."`);
  lines.push('schema_type: APIReference');
  lines.push(`last_verified: ${generatedAt.slice(0, 10)}`);
  lines.push('auto_extracted_source: "static/sdk-manifest.json"');
  lines.push('stability: stable');
  lines.push('last_breaking_change: 2026-05-19');
  lines.push('tags: [reference, mcp, auto-extracted]');
  lines.push('sidebar_position: 6');
  lines.push('---');
  lines.push('');
  lines.push(GENERATED_BANNER);
  lines.push('');
  lines.push(`# MCP server reference`);
  lines.push('');
  lines.push(`**Package**: \`@agirails/mcp-server@${mcp.package_version}\` · **Tools**: ${mcp.total} (5 discovery + 14 runtime + 1 protocol bootstrap) · **Manifest generated**: ${generatedAt.slice(0, 19).replace('T', ' ')} UTC`);
  lines.push('');
  lines.push('Install via `npx @agirails/mcp-server` and wire into any MCP-compatible client (Claude Desktop, Cursor, Cline, Windsurf, VS Code + MCP). See [Get AGIRAILS into your AI tool: MCP server](/start/ai-environment/mcp-server) for setup.');
  lines.push('');

  const renderLayer = (label: string, tools: typeof mcp.layers.discovery) => {
    lines.push(`## ${label}`);
    lines.push('');
    lines.push('| Tool | Description | Read-only | Destructive |');
    lines.push('|---|---|---|---|');
    for (const t of tools) {
      const desc = t.description.length > 140 ? t.description.slice(0, 137) + '…' : t.description;
      lines.push(`| \`${t.name}\` | ${desc} | ${t.read_only ? '✓' : ''} | ${t.destructive ? '⚠️' : ''} |`);
    }
    lines.push('');
  };

  renderLayer('Layer 1: Discovery (5 tools, read-only)', mcp.layers.discovery);
  renderLayer('Layer 2: Runtime (14 tools)', mcp.layers.runtime);
  renderLayer('Layer 3: Protocol bootstrap (1 tool)', mcp.layers.protocol);

  lines.push('## See also');
  lines.push('');
  lines.push('- [MCP server install](/start/ai-environment/mcp-server)');
  lines.push('- [Reference overview](/reference)');
  lines.push('- [Truth-ledger manifest (raw JSON)](/sdk-manifest.json)');
  lines.push('');

  return lines.join('\n');
}

interface CodeMerge {
  code: string;
  ts?: ErrorEntry;
  python?: ErrorEntry;
}

function mergeErrorsByCode(
  tsEntries: ErrorEntry[],
  pyEntries: ErrorEntry[],
): CodeMerge[] {
  const byCode = new Map<string, CodeMerge>();
  for (const e of tsEntries) {
    if (!e.code) continue;
    const entry = byCode.get(e.code) ?? { code: e.code };
    entry.ts = e;
    byCode.set(e.code, entry);
  }
  for (const e of pyEntries) {
    if (!e.code) continue;
    const entry = byCode.get(e.code) ?? { code: e.code };
    entry.python = e;
    byCode.set(e.code, entry);
  }
  return [...byCode.values()].sort((a, b) => a.code.localeCompare(b.code));
}

const RECOVERY_LABEL: Record<string, string> = {
  'retry-safe': '♻️ retry-safe',
  'user-action': '🛠️ user-action',
  'must-investigate': '🔍 must-investigate',
  'terminal': '⛔ terminal',
};

function renderTriageSection(
  lines: string[],
  tsEntries: ErrorEntry[],
  pyEntries: ErrorEntry[],
): void {
  const merged = mergeErrorsByCode(tsEntries, pyEntries);
  const withTriage = merged.filter((m) => m.ts?.cause || m.python?.cause);
  if (withTriage.length === 0) return;

  lines.push('## Per-code triage');
  lines.push('');
  lines.push(`${withTriage.length} user-facing error codes carry source-extracted **Cause** + **Fix** + **Recovery** tags. Each anchor below matches the raw error code string; paste the code (e.g. \`DEADLINE_EXPIRED\`) into your browser search or follow the direct fragment URL.`);
  lines.push('');

  for (const m of withTriage) {
    const triage = m.ts ?? m.python!;
    const anchor = m.code.toLowerCase();
    lines.push(`### \`${m.code}\` {#${anchor}}`);
    lines.push('');

    const classes: string[] = [];
    if (m.ts) classes.push(`**TS**: \`${m.ts.class_name}\``);
    if (m.python) classes.push(`**Python**: \`${m.python.class_name}\``);
    const recoveryRaw = (triage.recovery ?? '').trim();
    const recoveryLabel = RECOVERY_LABEL[recoveryRaw] ?? (recoveryRaw ? `_${recoveryRaw}_` : '_(unspecified)_');
    classes.push(`**Recovery**: ${recoveryLabel}`);
    lines.push(classes.join(' · '));
    lines.push('');

    if (triage.cause) {
      lines.push(`**Cause.** ${triage.cause}`);
      lines.push('');
    }
    if (triage.fix) {
      lines.push(`**Fix.** ${triage.fix}`);
      lines.push('');
    }
  }
}

function renderSymptomFallback(lines: string[]): void {
  lines.push('## If you don\'t have an error code');
  lines.push('');
  lines.push('Sometimes the SDK is silent or the failure mode looks like nothing in particular. Common scenarios:');
  lines.push('');
  lines.push('- **Agent appears to start but never picks up jobs.** Check `agent.status`, confirm `network:` matches the chain your service was registered on, and verify the AgentRegistry record at `agent.address` resolves. Setup-time issues most commonly surface as a [ServiceConfigError](#service_config_error) or [AgentLifecycleError](#agent_lifecycle_error); silent hangs usually mean RPC misconfiguration or unfunded paymaster.');
  lines.push('- **Transaction stuck in `INITIATED` or `QUOTED`.** No on-chain action will move it. Either the requester needs to `acceptQuote + linkEscrow`, or the deadline will eventually fire a [DEADLINE_EXPIRED](#deadline_expired). See [State machine](/protocol/state-machine).');
  lines.push('- **Money locked, can\'t move it.** Read `getTransaction(txId).state`. If `COMMITTED`/`IN_PROGRESS`/`DELIVERED`, the protocol path forward is `transitionState(...)` or `dispute(...)`. See [Dispute flow](/recipes/dispute-flow).');
  lines.push('- **`actp test` passes but production fails.** Almost always a config drift. Run `actp deploy:check --strict` and verify keystore network matches code-level `network:`.');
  lines.push('');
  lines.push('If none of these apply, [open an issue](https://github.com/agirails/sdk-js/issues) with the silent-failure repro and the output of `actp deploy:check --json`.');
  lines.push('');
}

function renderErrorsPage(errors: Manifest['errors'], generatedAt: string): string {
  const lines: string[] = [];
  lines.push('---');
  lines.push('slug: /reference/errors');
  lines.push('title: "Error reference"');
  lines.push(`description: "All ${errors.counts.ts} TypeScript + ${errors.counts.python} Python error classes. Auto-extracted from both SDK sources via the truth-ledger pipeline, with cross-SDK divergences surfaced."`);
  lines.push('schema_type: APIReference');
  lines.push(`last_verified: ${generatedAt.slice(0, 10)}`);
  lines.push('auto_extracted_source: "static/sdk-manifest.json"');
  lines.push('stability: stable');
  lines.push('last_breaking_change: 2026-05-19');
  lines.push('tags: [reference, errors, auto-extracted]');
  lines.push('sidebar_position: 5');
  lines.push('---');
  lines.push('');
  lines.push(GENERATED_BANNER);
  lines.push('');
  lines.push('# Error reference');
  lines.push('');
  lines.push(`**TypeScript SDK**: ${errors.counts.ts} error classes · **Python SDK**: ${errors.counts.python} error classes · **Manifest generated**: ${generatedAt.slice(0, 19).replace('T', ' ')} UTC`);
  lines.push('');
  lines.push('Every error in both SDKs extends from a common `ACTPError` (TS) / `ACTPError` (Python) base. The `code` column is the stable string identifier you can pattern-match against in `catch` blocks; this is preferred over `instanceof` checks for forward-compat. Errors without a `code` are abstract base classes that aren\'t thrown directly.');
  lines.push('');
  lines.push('**Got an error code?** Cmd+F or jump straight to its anchor in [Per-code triage](#per-code-triage) below: cause, fix, and recovery class auto-extracted from the SDK source comments. **No code yet?** See [If you don\'t have an error code](#if-you-dont-have-an-error-code).');
  lines.push('');

  // Per-code triage section: merge TS + Python entries by code so each code
  // gets one anchor with both class names listed. Built from the `@cause`,
  // `@fix`, and `@recovery` JSDoc/docstring tags extracted in errors.ts.
  renderTriageSection(lines, errors.ts, errors.python);

  renderSymptomFallback(lines);

  const renderTable = (sdk: 'TypeScript' | 'Python', entries: ErrorEntry[]) => {
    lines.push(`## ${sdk} SDK errors`);
    lines.push('');
    lines.push('| Class | Parent | Code | Source |');
    lines.push('|---|---|---|---|');
    const sorted = [...entries].sort((a, b) => a.class_name.localeCompare(b.class_name));
    for (const e of sorted) {
      const code = e.code ? `\`${e.code}\`` : '_(abstract)_';
      lines.push(`| \`${e.class_name}\` | \`${e.parent}\` | ${code} | \`${e.source_file}\` |`);
    }
    lines.push('');
  };

  renderTable('TypeScript', errors.ts);
  renderTable('Python', errors.python);

  if (errors.cross_sdk.ts_only.length > 0 || errors.cross_sdk.python_only.length > 0) {
    lines.push('## Cross-SDK divergences');
    lines.push('');
    lines.push('Errors that exist in one SDK but not the other. Some are intentional (TypeScript-side x402 payment integration errors don\'t apply to Python; Python-side circuit-breaker + Filebase + Arweave errors are runtime concerns the TS SDK doesn\'t share), others are gaps the [parity sprint](https://github.com/agirails/sdk-python) tracks.');
    lines.push('');
    if (errors.cross_sdk.ts_only.length > 0) {
      lines.push(`**TypeScript-only** (${errors.cross_sdk.ts_only.length}):`);
      lines.push('');
      lines.push(errors.cross_sdk.ts_only.map((c) => `\`${c}\``).join(', '));
      lines.push('');
    }
    if (errors.cross_sdk.python_only.length > 0) {
      lines.push(`**Python-only** (${errors.cross_sdk.python_only.length}):`);
      lines.push('');
      lines.push(errors.cross_sdk.python_only.map((c) => `\`${c}\``).join(', '));
      lines.push('');
    }
  }

  lines.push('## See also');
  lines.push('');
  lines.push('- [Reference overview](/reference)');
  lines.push('- [SDK reference: TypeScript](/reference/sdk-js)');
  lines.push('- [SDK reference: Python](/reference/sdk-python)');
  lines.push('- [Truth-ledger manifest (raw JSON)](/sdk-manifest.json)');
  lines.push('');

  return lines.join('\n');
}

// Fallback badge for sync_status values that renderSymbolTable doesn't
// explicitly handle. Every value of `SyncStatus` (types.ts) is currently
// branched on at the call site, so this only fires if the type ever grows
// a new variant. Kept narrow on purpose. Labels for the four canonical
// statuses live at the call site (renderSymbolTable) where the per-SDK
// directional phrasing matters.
function syncBadge(status: string): string {
  return `_(${status})_`;
}

function tierIntro(tier: string): string {
  switch (tier) {
    case 'level0':
      return 'The smallest surface that produces a working transaction. If you\'re integrating for the first time, this is where to start. Three or four imports get you a fully functional consumer or provider agent.';
    case 'basic':
      return 'The high-level convenience layer: `Agent`, `pay()`, `request()`, `provide()`. For most integrations this is all you need; you only drop to lower tiers when you need to customise something the convenience layer doesn\'t expose.';
    case 'standard':
      return 'Production-stable surface for non-trivial integrations: adapters, builders, message-signing utilities, escrow + state-machine helpers, error classes, type definitions. If your code touches the kernel directly (rather than going through `Agent`), it lives here.';
    case 'advanced':
      return 'Lower-level building blocks rarely needed in application code: orchestrators, dedup stores, policy engines, raw runtime interfaces. Stable APIs but the contract is "you know what you\'re doing." Reach here only when the standard tier is genuinely insufficient.';
    case 'internal':
      return 'Implementation details exposed for testing or compatibility but **not part of the public API contract**. May change between minor versions. Don\'t depend on these in application code.';
    default:
      return '';
  }
}

function escapeMd(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function renderSymbolTable(
  symbols: SdkSymbol[],
  tiers: Manifest['tiers'],
  sdk: 'ts' | 'python',
): string[] {
  const lines: string[] = [];
  lines.push('| Symbol | Kind | Summary | Cross-SDK status |');
  lines.push('|---|---|---|---|');
  const sorted = [...symbols].sort((a, b) => a.name.localeCompare(b.name));
  for (const s of sorted) {
    const t = tiers[s.name];
    let status = '_(no parity record)_';
    if (t) {
      if (t.sync_status === 'in-sync') status = '✅ in-sync';
      else if (t.sync_status === 'local-ahead') {
        // local-ahead: TS has it, Python doesn't. These rows only land in
        // the TS doc (Python symbol list won't include the symbol at all).
        status = '🟢 TS-only (Python parity pending)';
      }
      else if (t.sync_status === 'remote-ahead') {
        // remote-ahead: Python has it, TS doesn't. These rows only land in
        // the Python doc. Prior phrasing said "TS has it; Python pending"
        // which was the inverse of what `remote-ahead` actually means.
        status = '🟢 Python-only (TS parity pending)';
      }
      else if (t.sync_status === 'diverged') status = '⚠️ diverged (cross-SDK signature mismatch)';
      else status = syncBadge(t.sync_status);
    }
    const kind = s.kind === 'export-from' ? '_re-export_' : (s.kind === 'unknown' ? '_(unknown)_' : `\`${s.kind}\``);
    const summary = s.doc_summary ? escapeMd(s.doc_summary) : '_(no summary)_';
    lines.push(`| \`${s.name}\` | ${kind} | ${summary} | ${status} |`);
  }
  return lines;
}

function renderSdkTsPage(
  tier: 'basic' | 'standard',
  manifest: Manifest,
  generatedAt: string,
): string {
  const sdk = manifest.sdk_api.ts;
  // Bucketing: basic page also includes level0 (since level0 is the smallest convenience surface);
  // standard page also includes advanced (so the long tail isn't hidden behind a separate stub).
  const buckets: Record<string, string[]> = {
    basic: ['level0', 'basic'],
    standard: ['standard', 'advanced'],
  };
  const includedTiers = buckets[tier];
  const symbols = sdk.symbols.filter((s) => includedTiers.includes(s.tier));

  const title = tier === 'basic' ? 'TypeScript SDK: Basic + Level 0' : 'TypeScript SDK: Standard + Advanced';
  const desc = tier === 'basic'
    ? `Convenience tier of @agirails/sdk@${sdk.package_version}: Level 0 imports (\`request\`, \`provide\`) plus the \`Agent\` class and basic \`pay()\` flow.`
    : `Production-stable surface of @agirails/sdk@${sdk.package_version}: adapters, builders, message-signing utilities, runtime helpers, plus the advanced building blocks.`;
  const slug = `/reference/sdk-js/${tier}`;
  const sidebar = tier === 'basic' ? 1 : 2;

  const lines: string[] = [];
  lines.push('---');
  lines.push(`slug: ${slug}`);
  lines.push(`title: "${title}"`);
  lines.push(`description: "${desc}"`);
  lines.push('schema_type: APIReference');
  lines.push(`last_verified: ${generatedAt.slice(0, 10)}`);
  lines.push('auto_extracted_source: "static/sdk-manifest.json"');
  lines.push('stability: stable');
  lines.push('last_breaking_change: 2026-05-19');
  lines.push('tags: [reference, sdk-js, typescript, auto-extracted]');
  lines.push(`sidebar_position: ${sidebar}`);
  lines.push('---');
  lines.push('');
  lines.push(GENERATED_BANNER);
  lines.push('');
  lines.push(`# ${title}`);
  lines.push('');
  lines.push(`**Package**: \`@agirails/sdk@${sdk.package_version}\` · **Symbols in this view**: ${symbols.length} · **Total TS surface**: ${sdk.count} · **Manifest generated**: ${generatedAt.slice(0, 19).replace('T', ' ')} UTC`);
  lines.push('');
  lines.push('Every entry below is **auto-extracted from the SDK source itself** via the truth-ledger pipeline. The cross-SDK status column tells you whether the symbol has a Python counterpart, is TS-only, or has signature drift the parity sprint is tracking.');
  lines.push('');
  lines.push('For detailed per-symbol docs (parameters, return types, examples) consult the source JSDoc in [`agirails/sdk-js`](https://github.com/agirails/sdk-js). Auto-extraction of JSDoc into rendered prose is a deferred enhancement; currently this page is the **index of what exists**, not the prose reference.');
  lines.push('');

  for (const t of includedTiers) {
    const tierSymbols = symbols.filter((s) => s.tier === t);
    if (tierSymbols.length === 0) continue;
    lines.push(`## ${t.charAt(0).toUpperCase() + t.slice(1)} tier (${tierSymbols.length} symbols)`);
    lines.push('');
    const intro = tierIntro(t);
    if (intro) {
      lines.push(intro);
      lines.push('');
    }
    lines.push(...renderSymbolTable(tierSymbols, manifest.tiers, 'ts'));
    lines.push('');
  }

  lines.push('## See also');
  lines.push('');
  lines.push('- [Python SDK reference](/reference/sdk-python)');
  if (tier === 'basic') {
    lines.push('- [TypeScript Standard + Advanced](/reference/sdk-js/standard)');
  } else {
    lines.push('- [TypeScript Basic + Level 0](/reference/sdk-js/basic)');
  }
  lines.push('- [Errors reference](/reference/errors): exception class catalog');
  lines.push('- [Truth-ledger manifest (raw JSON)](/sdk-manifest.json)');
  lines.push(`- [Source: \`@agirails/sdk@${sdk.package_version}\`](https://github.com/agirails/sdk-js)`);
  lines.push('');

  return lines.join('\n');
}

function renderSdkTsIndex(manifest: Manifest, generatedAt: string): string {
  const sdk = manifest.sdk_api.ts;
  const tierCounts: Record<string, number> = {};
  for (const s of sdk.symbols) tierCounts[s.tier] = (tierCounts[s.tier] ?? 0) + 1;

  const lines: string[] = [];
  lines.push('---');
  lines.push('slug: /reference/sdk-js');
  lines.push('title: "TypeScript SDK reference"');
  lines.push(`description: "Auto-extracted surface of @agirails/sdk@${sdk.package_version}, organised by tier (Level 0 → Basic → Standard → Advanced)."`);
  lines.push('schema_type: APIReference');
  lines.push(`last_verified: ${generatedAt.slice(0, 10)}`);
  lines.push('auto_extracted_source: "static/sdk-manifest.json"');
  lines.push('stability: stable');
  lines.push('last_breaking_change: 2026-05-19');
  lines.push('tags: [reference, sdk-js, typescript, auto-extracted]');
  lines.push('sidebar_position: 0');
  lines.push('---');
  lines.push('');
  lines.push(GENERATED_BANNER);
  lines.push('');
  lines.push('# TypeScript SDK reference');
  lines.push('');
  lines.push(`**Package**: \`@agirails/sdk@${sdk.package_version}\` · **Total symbols**: ${sdk.count} · **Source**: \`${sdk.source_file}\``);
  lines.push('');
  lines.push('<img src="/img/diagrams/three-tier-api.svg" alt="Three-tier SDK API: Level 0, Basic, Standard with Advanced/Internal beyond" style={{maxWidth: \'100%\', height: \'auto\', margin: \'1.5rem 0\'}} />');
  lines.push('');
  lines.push('The TypeScript SDK is tiered to match the depth of integration you need:');
  lines.push('');
  lines.push('| Tier | Symbols | When to use |');
  lines.push('|---|---|---|');
  lines.push(`| **[Level 0 + Basic](/reference/sdk-js/basic)** | ${(tierCounts['level0'] ?? 0) + (tierCounts['basic'] ?? 0)} | First integration, convenience layer (\`Agent\`, \`request\`, \`provide\`, \`pay()\`) |`);
  lines.push(`| **[Standard + Advanced](/reference/sdk-js/standard)** | ${(tierCounts['standard'] ?? 0) + (tierCounts['advanced'] ?? 0)} | Production-stable depth: adapters, builders, signers, runtime helpers, orchestrators |`);
  lines.push(`| _Internal_ | ${tierCounts['internal'] ?? 0} | Not part of the public API contract; documented separately if at all |`);
  lines.push('');
  lines.push('## Quick orientation');
  lines.push('');
  lines.push('Three entry points cover most real code:');
  lines.push('');
  lines.push('```ts');
  lines.push('// 1. Level 0: one-shot request / provide, no Agent lifecycle');
  lines.push('import { request, provide } from \'@agirails/sdk\';');
  lines.push('');
  lines.push('// 2. Basic: long-lived agent with handlers');
  lines.push('import { Agent } from \'@agirails/sdk\';');
  lines.push('');
  lines.push('// 3. Standard: direct adapter / builder usage');
  lines.push('import { ACTPClient, CounterOfferBuilder, StandardAdapter } from \'@agirails/sdk\';');
  lines.push('```');
  lines.push('');
  lines.push('Pick the lowest tier that covers your use case; you can always drop deeper if needed.');
  lines.push('');
  lines.push('## See also');
  lines.push('');
  lines.push('- [Python SDK reference](/reference/sdk-python)');
  lines.push('- [Errors reference](/reference/errors)');
  lines.push('- [CLI reference](/reference/cli)');
  lines.push('- [Consumer agent recipe](/recipes/consumer-agent): Level 0 / Basic in practice');
  lines.push('- [Provider agent recipe](/recipes/provider-agent): Level 0 / Basic in practice');
  lines.push('');

  return lines.join('\n');
}

function renderSdkPythonPage(manifest: Manifest, generatedAt: string): string {
  const sdk = manifest.sdk_api.python;
  const tierCounts: Record<string, number> = {};
  for (const s of sdk.symbols) tierCounts[s.tier] = (tierCounts[s.tier] ?? 0) + 1;

  // Python sidebar exposes only a single page, so we render all tiers here
  // (except 'internal') as separate sections.
  const tiersToRender = ['level0', 'basic', 'standard', 'advanced'];

  const lines: string[] = [];
  lines.push('---');
  lines.push('slug: /reference/sdk-python');
  lines.push('title: "Python SDK reference"');
  lines.push(`description: "Auto-extracted surface of agirails@${sdk.package_version}, organised by tier (Level 0 → Basic → Standard → Advanced)."`);
  lines.push('schema_type: APIReference');
  lines.push(`last_verified: ${generatedAt.slice(0, 10)}`);
  lines.push('auto_extracted_source: "static/sdk-manifest.json"');
  lines.push('stability: stable');
  lines.push('last_breaking_change: 2026-05-19');
  lines.push('tags: [reference, sdk-python, auto-extracted]');
  lines.push('sidebar_position: 4');
  lines.push('---');
  lines.push('');
  lines.push(GENERATED_BANNER);
  lines.push('');
  lines.push('# Python SDK reference');
  lines.push('');
  lines.push(`**Package**: \`agirails@${sdk.package_version}\` · **Total symbols**: ${sdk.count} · **Manifest generated**: ${generatedAt.slice(0, 19).replace('T', ' ')} UTC`);
  lines.push('');
  lines.push('Every entry below is **auto-extracted from the SDK source itself** via the truth-ledger pipeline. The cross-SDK status column tells you whether the symbol has a TypeScript counterpart, is Python-only, or has signature drift the parity sprint is tracking.');
  lines.push('');
  lines.push('For detailed per-symbol docs (parameters, return types, examples) consult the source docstrings in [`agirails/sdk-python`](https://github.com/agirails/sdk-python). Auto-extraction of docstrings into rendered prose is a deferred enhancement; currently this page is the **index of what exists**, not the prose reference.');
  lines.push('');
  lines.push('## Tier distribution');
  lines.push('');
  lines.push('| Tier | Symbols |');
  lines.push('|---|---|');
  for (const t of tiersToRender) {
    lines.push(`| [${t.charAt(0).toUpperCase() + t.slice(1)}](#${t}-tier) | ${tierCounts[t] ?? 0} |`);
  }
  if (tierCounts['internal']) {
    lines.push(`| _Internal_ (not in this view) | ${tierCounts['internal']} |`);
  }
  lines.push('');

  lines.push('## Quick orientation');
  lines.push('');
  lines.push('```python');
  lines.push('# Level 0: one-shot request / provide');
  lines.push('from agirails import request, provide');
  lines.push('');
  lines.push('# Basic: long-lived agent with handlers');
  lines.push('from agirails import Agent');
  lines.push('');
  lines.push('# Standard: direct kernel / adapter usage');
  lines.push('from agirails import ACTPClient, CounterOfferMessage');
  lines.push('```');
  lines.push('');

  for (const t of tiersToRender) {
    const tierSymbols = sdk.symbols.filter((s) => s.tier === t);
    if (tierSymbols.length === 0) continue;
    lines.push(`## ${t.charAt(0).toUpperCase() + t.slice(1)} tier {#${t}-tier}`);
    lines.push('');
    const intro = tierIntro(t);
    if (intro) {
      lines.push(intro);
      lines.push('');
    }
    lines.push(`**${tierSymbols.length} symbols.**`);
    lines.push('');
    lines.push(...renderSymbolTable(tierSymbols, manifest.tiers, 'python'));
    lines.push('');
  }

  lines.push('## See also');
  lines.push('');
  lines.push('- [TypeScript SDK reference](/reference/sdk-js)');
  lines.push('- [Errors reference](/reference/errors)');
  lines.push('- [CLI reference](/reference/cli)');
  lines.push('- [Consumer agent recipe](/recipes/consumer-agent)');
  lines.push('- [Provider agent recipe](/recipes/provider-agent)');
  lines.push(`- [Source: \`agirails@${sdk.package_version}\`](https://github.com/agirails/sdk-python)`);
  lines.push('');

  return lines.join('\n');
}

function renderAgirailsMdV4Page(p: ProtocolData, generatedAt: string): string {
  const lines: string[] = [];
  lines.push('---');
  lines.push('slug: /reference/agirails-md-v4');
  lines.push('title: "AGIRAILS.md V4 schema"');
  lines.push(`description: "Field-by-field reference for the V4 frontmatter schema parsed by parseAgirailsMdV4. Auto-extracted from the canonical AGIRAILS.md spec (${p.protocol} v${p.version}, spec=${p.spec})."`);
  lines.push('schema_type: APIReference');
  lines.push(`last_verified: ${generatedAt.slice(0, 10)}`);
  lines.push('auto_extracted_source: "static/sdk-manifest.json (protocol surface)"');
  lines.push('stability: stable');
  lines.push('last_breaking_change: 2026-05-19');
  lines.push('tags: [reference, agirails-md, V4-schema, auto-extracted]');
  lines.push('sidebar_position: 7');
  lines.push('---');
  lines.push('');
  lines.push(GENERATED_BANNER);
  lines.push('');
  lines.push('# AGIRAILS.md V4 schema');
  lines.push('');
  lines.push(`**${p.protocol} v${p.version}** · spec \`${p.spec}\` · network \`${p.network}\` · currency \`${p.currency}\` · fee \`${p.fee}\` · **Manifest generated**: ${generatedAt.slice(0, 19).replace('T', ' ')} UTC`);
  lines.push('');
  lines.push('This page is the auto-extracted reference for the canonical AGIRAILS.md V4 frontmatter: the schema that `parseAgirailsMdV4` validates against. Two artefacts use this schema:');
  lines.push('');
  lines.push('- **Owner-local AGIRAILS.md**: template-filled copy of the canonical spec, kept locally per agent.');
  lines.push('- **`{slug}.md` covenant**: public business card, V4-schema'  + ', hash-anchored on-chain via AgentRegistry.');
  lines.push('');
  lines.push('See [the covenant page](/protocol/covenant) for the mental model + the [AGIRAILS.md spec page](/protocol/agirails-md) for the three-form disambiguation (canonical / owner-local / covenant).');
  lines.push('');

  // SDK pins
  lines.push('## SDK pins');
  lines.push('');
  lines.push('| SDK | Package | Version |');
  lines.push('|---|---|---|');
  if (p.sdk.npm) lines.push(`| TypeScript | \`${p.sdk.npm}\` | per [/reference/sdk-js](/reference/sdk-js) |`);
  if (p.sdk.pip) lines.push(`| Python | \`${p.sdk.pip}\` | per [/reference/sdk-python](/reference/sdk-python) |`);
  lines.push('');

  // States
  lines.push(`## State machine (${p.states.length} states)`);
  lines.push('');
  lines.push('| Value | Name | Description |');
  lines.push('|---:|---|---|');
  for (const s of p.states) {
    lines.push(`| ${s.value} | \`${s.name}\` | ${s.description} |`);
  }
  lines.push('');
  lines.push('See [State machine](/protocol/state-machine) for the DAG (transitions + access control).');
  lines.push('');

  // Capabilities
  lines.push(`## Capabilities (${p.capabilities.length})`);
  lines.push('');
  lines.push('Free-form `services` array values that the canonical spec recognises as well-known capability tags. Agents may declare additional service names; these are the curated list:');
  lines.push('');
  lines.push(p.capabilities.map((c) => `\`${c}\``).join(', ') + '.');
  lines.push('');

  // Onboarding questions
  lines.push(`## Onboarding questions (${p.onboarding.questions.length})`);
  lines.push('');
  lines.push(`Execution mode: \`${p.onboarding.execution}\`. The canonical spec defines these questions that the LLM-onboarded path walks to fill the covenant. The CLI \`actp init\` accepts the same data via flags rather than prompts.`);
  lines.push('');
  lines.push('| # | ID | Question | Type | Default | Condition | Advanced |');
  lines.push('|---:|---|---|---|---|---|---|');
  p.onboarding.questions.forEach((q, i) => {
    const def = q.default !== undefined ? `\`${q.default}\`` : '_(none)_';
    const cond = q.condition ? `\`${q.condition}\`` : '_(none)_';
    const adv = q.advanced ? '✓' : '';
    const typeWithOpts = q.options ? `${q.type} (${q.options.join(' / ')})` : q.type;
    lines.push(`| ${i + 1} | \`${q.id}\` | ${q.ask} | \`${typeWithOpts}\` | ${def} | ${cond} | ${adv} |`);
  });
  lines.push('');

  // See also
  lines.push('## See also');
  lines.push('');
  lines.push('- [Canonical AGIRAILS.md spec](/protocol/agirails-md): three-form disambiguation');
  lines.push('- [The `{slug}.md` covenant](/protocol/covenant): V4 business card');
  lines.push('- [State machine](/protocol/state-machine): 8-state DAG');
  lines.push('- [Get started](/start): 5-input flow that fills the covenant');
  lines.push('- [Truth-ledger manifest (raw JSON)](/sdk-manifest.json): `protocol` section');
  lines.push('');

  return lines.join('\n');
}

function writeFile(relPath: string, content: string): void {
  const fullPath = path.join(DOCS_DIR, relPath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content, 'utf-8');
  console.log(`[render-reference] wrote ${relPath}`);
}

function main(): void {
  console.log('[render-reference] loading manifest from', MANIFEST_PATH);
  const m = loadManifest();
  console.log(`[render-reference] manifest _generatedAt: ${m._generatedAt}`);

  writeFile('reference/contracts/base-mainnet.md', renderContractsPage('base-mainnet', m.contracts['base-mainnet'], m._generatedAt));
  writeFile('reference/contracts/base-sepolia.md', renderContractsPage('base-sepolia', m.contracts['base-sepolia'], m._generatedAt));
  writeFile('reference/cli/index.md', renderCliPage(m.cli, m._generatedAt));
  writeFile('reference/mcp-server/index.md', renderMcpPage(m.mcp, m._generatedAt));
  writeFile('reference/errors/index.md', renderErrorsPage(m.errors, m._generatedAt));
  writeFile('reference/sdk-js/index.md', renderSdkTsIndex(m, m._generatedAt));
  writeFile('reference/sdk-js/basic.md', renderSdkTsPage('basic', m, m._generatedAt));
  writeFile('reference/sdk-js/standard.md', renderSdkTsPage('standard', m, m._generatedAt));
  writeFile('reference/sdk-python/index.md', renderSdkPythonPage(m, m._generatedAt));
  writeFile('reference/agirails-md-v4.md', renderAgirailsMdV4Page(m.protocol, m._generatedAt));

  console.log('[render-reference] done');
}

main();
