#!/usr/bin/env tsx
/**
 * Renders auto-extracted reference pages from static/sdk-manifest.json.
 *
 * Currently renders:
 *   - docs/reference/contracts/base-mainnet.md
 *   - docs/reference/contracts/base-sepolia.md
 *   - docs/reference/cli/index.md  (TS + Python command tables)
 *   - docs/reference/mcp-server/index.md  (20 tools by layer)
 *
 * Other /reference/ pages stay hand-written for v1 per PHASE3_DECISIONS Q3
 * (auto-extract SDK API + errors is a post-v1 stream).
 *
 * Run via:
 *   npm run render-reference
 *
 * Wired into the CI workflow (truth-ledger-refresh.yml) so manifest
 * regeneration + reference re-render ship together as a single PR.
 *
 * Does NOT run in Vercel prebuild — like truth-ledger itself, this script
 * needs the manifest to exist (it always does, since it's committed).
 * Vercel just deploys whatever rendered pages are committed.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const ROOT = path.resolve(__dirname, '..');
const MANIFEST_PATH = path.join(ROOT, 'static', 'sdk-manifest.json');
const DOCS_DIR = path.join(ROOT, 'docs');

interface ContractEntry {
  address: string;
  verified_status: string;
  verified_at?: string;
  deployment_claimed_verified?: boolean;
  deploy_block?: number;
  deploy_tx?: string;
  explorer_url?: string;
  compiler?: string;
  status?: 'deprecated';
  note?: string;
  platformFeeBps?: number;
  disputeBondBps?: number;
  minDisputeBondMicroUSDC?: number;
  owner?: string;
}

interface ErrorEntry {
  class_name: string;
  parent: string;
  code: string | null;
  source_file: string;
}

interface Manifest {
  _generatedAt: string;
  _sourceVersions: Record<string, string>;
  contracts: Record<string, {
    chainId: number;
    blockExplorer: string;
    contracts: Record<string, ContractEntry>;
  }>;
  cli: {
    ts: { binary: string; commands: { name: string; qualified_name: string; subcommands?: { name: string; qualified_name: string }[] }[]; };
    python: { binary: string; commands: { name: string; qualified_name: string; subcommands?: { name: string; qualified_name: string }[] }[]; };
    cross_sdk: { ts_only: string[]; python_only: string[] };
    counts: { ts: number; python: number };
  };
  mcp: {
    package_version: string;
    total: number;
    layers: {
      discovery: { name: string; description: string; read_only: boolean; destructive: boolean }[];
      runtime: { name: string; description: string; read_only: boolean; destructive: boolean }[];
      protocol: { name: string; description: string; read_only: boolean; destructive: boolean }[];
    };
  };
  errors: {
    ts: ErrorEntry[];
    python: ErrorEntry[];
    cross_sdk: { ts_only: string[]; python_only: string[] };
    counts: { ts: number; python: number };
  };
}

const GENERATED_BANNER = '<!-- GENERATED by scripts/render-reference.ts from static/sdk-manifest.json. Do not edit by hand. -->';

function loadManifest(): Manifest {
  if (!fs.existsSync(MANIFEST_PATH)) {
    throw new Error(`Manifest not found: ${MANIFEST_PATH}. Run npm run truth-ledger first.`);
  }
  return JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8'));
}

function verifiedBadge(status: string): string {
  switch (status) {
    case 'exact_match': return '✅ Sourcify exact match';
    case 'partial_match': return '⚠️ Sourcify partial match';
    case 'no_match': return '❌ Sourcify no match';
    case 'deployment_claim_only': return '⏳ Deployment-claim only (Sourcify unreachable at last check)';
    case 'unverified': return '🔓 Not verified';
    case 'external_token': return '🏛️ External token (Circle USDC etc.)';
    default: return status;
  }
}

function renderContractsPage(
  network: 'base-mainnet' | 'base-sepolia',
  data: Manifest['contracts'][string],
  generatedAt: string,
): string {
  const title = network === 'base-mainnet' ? 'Base mainnet contracts (chain 8453)' : 'Base Sepolia contracts (chain 84532)';
  const description = network === 'base-mainnet'
    ? 'Production ACTP kernel + supporting contracts on Base mainnet, with live Sourcify exact-match verification.'
    : 'Test ACTP kernel + supporting contracts on Base Sepolia, with live Sourcify exact-match verification.';

  const lines: string[] = [];
  lines.push('---');
  lines.push(`slug: /reference/contracts/${network}`);
  lines.push(`title: "${title}"`);
  lines.push(`description: "${description}"`);
  lines.push('schema_type: APIReference');
  lines.push(`last_verified: ${generatedAt.slice(0, 10)}`);
  lines.push('auto_extracted_source: "static/sdk-manifest.json"');
  lines.push('tags: [reference, contracts, ' + network + ', auto-extracted]');
  lines.push('sidebar_position: ' + (network === 'base-mainnet' ? 1 : 2));
  lines.push('---');
  lines.push('');
  lines.push(GENERATED_BANNER);
  lines.push('');
  lines.push(`# ${title}`);
  lines.push('');
  lines.push(description);
  lines.push('');
  lines.push(`**Chain ID**: \`${data.chainId}\` · **Block explorer**: [${data.blockExplorer}](${data.blockExplorer}) · **Manifest generated**: ${generatedAt.slice(0, 19).replace('T', ' ')} UTC`);
  lines.push('');

  for (const [name, c] of Object.entries(data.contracts)) {
    lines.push(`## ${name}`);
    lines.push('');
    lines.push(`**Address**: [\`${c.address}\`](${c.explorer_url ?? data.blockExplorer + '/address/' + c.address})`);
    lines.push('');
    lines.push(`**Verification**: ${verifiedBadge(c.verified_status)}` + (c.verified_at ? ` _(checked ${c.verified_at.slice(0, 19).replace('T', ' ')} UTC)_` : ''));
    lines.push('');
    if (c.status === 'deprecated') {
      lines.push(':::warning Deprecated');
      lines.push('This contract is marked deprecated and retained only for legacy integration paths. Do not use for new code.');
      lines.push(':::');
      lines.push('');
    }
    const metaRows: string[] = [];
    if (c.deploy_block !== undefined) metaRows.push(`| Deploy block | \`${c.deploy_block}\` |`);
    if (c.deploy_tx) metaRows.push(`| Deploy tx | [\`${c.deploy_tx.slice(0, 14)}…\`](${data.blockExplorer}/tx/${c.deploy_tx}) |`);
    if (c.compiler) metaRows.push(`| Solidity compiler | \`${c.compiler}\` |`);
    if (c.platformFeeBps !== undefined) metaRows.push(`| platformFeeBps | \`${c.platformFeeBps}\` (${c.platformFeeBps / 100}%) |`);
    if (c.disputeBondBps !== undefined) metaRows.push(`| disputeBondBps | \`${c.disputeBondBps}\` (${c.disputeBondBps / 100}%) |`);
    if (c.minDisputeBondMicroUSDC !== undefined) metaRows.push(`| MIN_DISPUTE_BOND | \`${c.minDisputeBondMicroUSDC / 1_000_000}\` USDC |`);
    if (c.owner) metaRows.push(`| Owner | \`${c.owner}\` |`);
    if (metaRows.length > 0) {
      lines.push('| Field | Value |');
      lines.push('|---|---|');
      lines.push(...metaRows);
      lines.push('');
    }
    if (c.note) {
      lines.push(`> ${c.note.replace(/\n/g, ' ')}`);
      lines.push('');
    }
  }

  lines.push('## See also');
  lines.push('');
  lines.push('- [Truth-ledger manifest (raw JSON)](/sdk-manifest.json)');
  lines.push(`- [${network === 'base-mainnet' ? 'Base Sepolia contracts' : 'Base mainnet contracts'}](/reference/contracts/${network === 'base-mainnet' ? 'base-sepolia' : 'base-mainnet'})`);
  lines.push('- [Protocol fees + dispute bonds](/protocol/fees)');
  lines.push('- [Escrow mechanism](/protocol/escrow)');
  lines.push('');

  return lines.join('\n');
}

function renderCliPage(cli: Manifest['cli'], generatedAt: string): string {
  const lines: string[] = [];
  lines.push('---');
  lines.push('slug: /reference/cli');
  lines.push('title: "actp CLI reference"');
  lines.push('description: "All actp subcommands, args, and options — auto-extracted from sdk-js (Commander) + python-sdk-v2 (Typer) sources via the truth-ledger pipeline."');
  lines.push('schema_type: APIReference');
  lines.push(`last_verified: ${generatedAt.slice(0, 10)}`);
  lines.push('auto_extracted_source: "static/sdk-manifest.json"');
  lines.push('tags: [reference, cli, auto-extracted]');
  lines.push('sidebar_position: 1');
  lines.push('---');
  lines.push('');
  lines.push(GENERATED_BANNER);
  lines.push('');
  lines.push('# actp CLI reference');
  lines.push('');
  lines.push(`**TypeScript SDK CLI** (\`${cli.ts.binary}\`): ${cli.counts.ts} commands · **Python SDK CLI** (\`${cli.python.binary}\`): ${cli.counts.python} commands · **Manifest generated**: ${generatedAt.slice(0, 19).replace('T', ' ')} UTC`);
  lines.push('');
  lines.push('Both SDKs expose the same `actp` binary, with the command tree extracted directly from each runtime\'s Commander/Typer registration.');
  lines.push('');

  const renderCmds = (sdk: 'TS' | 'Python', commands: typeof cli.ts.commands) => {
    lines.push(`## ${sdk} CLI commands`);
    lines.push('');
    lines.push('| Command | Subcommands |');
    lines.push('|---|---|');
    for (const c of commands) {
      const subs = c.subcommands && c.subcommands.length > 0
        ? c.subcommands.map((s) => `\`${s.qualified_name}\``).join(', ')
        : '—';
      lines.push(`| \`actp ${c.name}\` | ${subs} |`);
    }
    lines.push('');
  };

  renderCmds('TS', cli.ts.commands);
  renderCmds('Python', cli.python.commands);

  if (cli.cross_sdk.ts_only.length > 0 || cli.cross_sdk.python_only.length > 0) {
    lines.push('## Cross-SDK divergences');
    lines.push('');
    if (cli.cross_sdk.ts_only.length > 0) {
      lines.push(`**TypeScript-only** (${cli.cross_sdk.ts_only.length}): ${cli.cross_sdk.ts_only.map((c) => `\`${c}\``).join(', ')}`);
      lines.push('');
    }
    if (cli.cross_sdk.python_only.length > 0) {
      lines.push(`**Python-only** (${cli.cross_sdk.python_only.length}): ${cli.cross_sdk.python_only.map((c) => `\`${c}\``).join(', ')}`);
      lines.push('');
    }
  }

  lines.push('## See also');
  lines.push('');
  lines.push('- [Reference overview](/reference)');
  lines.push('- [Truth-ledger manifest (raw JSON)](/sdk-manifest.json)');
  lines.push('');

  return lines.join('\n');
}

function renderMcpPage(mcp: Manifest['mcp'], generatedAt: string): string {
  const lines: string[] = [];
  lines.push('---');
  lines.push('slug: /reference/mcp-server');
  lines.push('title: "MCP server reference (@agirails/mcp-server)"');
  lines.push(`description: "All ${mcp.total} MCP tools across three layers (discovery, runtime, protocol bootstrap) — auto-extracted from the mcp-server TOOLS array."`);
  lines.push('schema_type: APIReference');
  lines.push(`last_verified: ${generatedAt.slice(0, 10)}`);
  lines.push('auto_extracted_source: "static/sdk-manifest.json"');
  lines.push('tags: [reference, mcp, auto-extracted]');
  lines.push('sidebar_position: 6');
  lines.push('---');
  lines.push('');
  lines.push(GENERATED_BANNER);
  lines.push('');
  lines.push(`# MCP server reference`);
  lines.push('');
  lines.push(`**Package**: \`@agirails/mcp-server@${mcp.package_version}\` · **Tools**: ${mcp.total} (5 discovery + 14 runtime + 1 protocol bootstrap) · **Manifest generated**: ${generatedAt.slice(0, 19).replace('T', ' ')} UTC`);
  lines.push('');
  lines.push('Install via `npx @agirails/mcp-server` and wire into any MCP-compatible client (Claude Desktop, Cursor, Cline, Windsurf, VS Code + MCP). See [Get AGIRAILS into your AI tool — MCP server](/start/ai-environment/mcp-server) for setup.');
  lines.push('');

  const renderLayer = (label: string, tools: typeof mcp.layers.discovery) => {
    lines.push(`## ${label}`);
    lines.push('');
    lines.push('| Tool | Description | Read-only | Destructive |');
    lines.push('|---|---|---|---|');
    for (const t of tools) {
      const desc = t.description.length > 140 ? t.description.slice(0, 137) + '…' : t.description;
      lines.push(`| \`${t.name}\` | ${desc} | ${t.read_only ? '✓' : ''} | ${t.destructive ? '⚠️' : ''} |`);
    }
    lines.push('');
  };

  renderLayer('Layer 1 — Discovery (5 tools, read-only)', mcp.layers.discovery);
  renderLayer('Layer 2 — Runtime (14 tools)', mcp.layers.runtime);
  renderLayer('Layer 3 — Protocol bootstrap (1 tool)', mcp.layers.protocol);

  lines.push('## See also');
  lines.push('');
  lines.push('- [MCP server install](/start/ai-environment/mcp-server)');
  lines.push('- [Reference overview](/reference)');
  lines.push('- [Truth-ledger manifest (raw JSON)](/sdk-manifest.json)');
  lines.push('');

  return lines.join('\n');
}

function renderErrorsPage(errors: Manifest['errors'], generatedAt: string): string {
  const lines: string[] = [];
  lines.push('---');
  lines.push('slug: /reference/errors');
  lines.push('title: "Error reference"');
  lines.push(`description: "All ${errors.counts.ts} TypeScript + ${errors.counts.python} Python error classes — auto-extracted from both SDK sources via the truth-ledger pipeline, with cross-SDK divergences surfaced."`);
  lines.push('schema_type: APIReference');
  lines.push(`last_verified: ${generatedAt.slice(0, 10)}`);
  lines.push('auto_extracted_source: "static/sdk-manifest.json"');
  lines.push('tags: [reference, errors, auto-extracted]');
  lines.push('sidebar_position: 5');
  lines.push('---');
  lines.push('');
  lines.push(GENERATED_BANNER);
  lines.push('');
  lines.push('# Error reference');
  lines.push('');
  lines.push(`**TypeScript SDK**: ${errors.counts.ts} error classes · **Python SDK**: ${errors.counts.python} error classes · **Manifest generated**: ${generatedAt.slice(0, 19).replace('T', ' ')} UTC`);
  lines.push('');
  lines.push('Every error in both SDKs extends from a common `ACTPError` (TS) / `ACTPError` (Python) base. The `code` column is the stable string identifier you can pattern-match against in `catch` blocks — preferred over `instanceof` checks for forward-compat. Errors without a `code` are abstract base classes that aren\'t thrown directly.');
  lines.push('');

  const renderTable = (sdk: 'TypeScript' | 'Python', entries: ErrorEntry[]) => {
    lines.push(`## ${sdk} SDK errors`);
    lines.push('');
    lines.push('| Class | Parent | Code | Source |');
    lines.push('|---|---|---|---|');
    const sorted = [...entries].sort((a, b) => a.class_name.localeCompare(b.class_name));
    for (const e of sorted) {
      const code = e.code ? `\`${e.code}\`` : '_(abstract)_';
      lines.push(`| \`${e.class_name}\` | \`${e.parent}\` | ${code} | \`${e.source_file}\` |`);
    }
    lines.push('');
  };

  renderTable('TypeScript', errors.ts);
  renderTable('Python', errors.python);

  if (errors.cross_sdk.ts_only.length > 0 || errors.cross_sdk.python_only.length > 0) {
    lines.push('## Cross-SDK divergences');
    lines.push('');
    lines.push('Errors that exist in one SDK but not the other. Some are intentional (TypeScript-side x402 payment integration errors don\'t apply to Python; Python-side circuit-breaker + Filebase + Arweave errors are runtime concerns the TS SDK doesn\'t share), others are gaps the [parity sprint](https://github.com/agirails/sdk-python) tracks.');
    lines.push('');
    if (errors.cross_sdk.ts_only.length > 0) {
      lines.push(`**TypeScript-only** (${errors.cross_sdk.ts_only.length}):`);
      lines.push('');
      lines.push(errors.cross_sdk.ts_only.map((c) => `\`${c}\``).join(', '));
      lines.push('');
    }
    if (errors.cross_sdk.python_only.length > 0) {
      lines.push(`**Python-only** (${errors.cross_sdk.python_only.length}):`);
      lines.push('');
      lines.push(errors.cross_sdk.python_only.map((c) => `\`${c}\``).join(', '));
      lines.push('');
    }
  }

  lines.push('## See also');
  lines.push('');
  lines.push('- [Reference overview](/reference)');
  lines.push('- [SDK reference — TypeScript](/reference/sdk-js)');
  lines.push('- [SDK reference — Python](/reference/sdk-python)');
  lines.push('- [Truth-ledger manifest (raw JSON)](/sdk-manifest.json)');
  lines.push('');

  return lines.join('\n');
}

function writeFile(relPath: string, content: string): void {
  const fullPath = path.join(DOCS_DIR, relPath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content, 'utf-8');
  console.log(`[render-reference] wrote ${relPath}`);
}

function main(): void {
  console.log('[render-reference] loading manifest from', MANIFEST_PATH);
  const m = loadManifest();
  console.log(`[render-reference] manifest _generatedAt: ${m._generatedAt}`);

  writeFile('reference/contracts/base-mainnet.md', renderContractsPage('base-mainnet', m.contracts['base-mainnet'], m._generatedAt));
  writeFile('reference/contracts/base-sepolia.md', renderContractsPage('base-sepolia', m.contracts['base-sepolia'], m._generatedAt));
  writeFile('reference/cli/index.md', renderCliPage(m.cli, m._generatedAt));
  writeFile('reference/mcp-server/index.md', renderMcpPage(m.mcp, m._generatedAt));
  writeFile('reference/errors/index.md', renderErrorsPage(m.errors, m._generatedAt));

  console.log('[render-reference] done');
}

main();
